"""Initial migrate

Revision ID: 4d21d15fe4c3
Revises: 
Create Date: 2025-11-23 15:20:24.332660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d21d15fe4c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=100), nullable=False),
    sa.Column('birth_year', sa.DateTime(), nullable=False),
    sa.Column('death_year', sa.DateTime(), nullable=True),
    sa.Column('nationality', sa.Enum('IRAN', 'UNITED_STATES', 'UNITED_KINGDOM', 'GERMANY', 'FRANCE', 'JAPAN', 'CHINA', 'SOUTH_KOREA', 'INDIA', name='country'), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_author'))
    )
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genres')),
    sa.UniqueConstraint('name', name=op.f('uq_genres_name'))
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BANNED', 'SUSPENDED', 'PENDING', 'DELETED', 'EXPIRED', name='status'), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_members')),
    sa.UniqueConstraint('email', name=op.f('uq_members_email')),
    sa.UniqueConstraint('username', name=op.f('uq_members_username'))
    )
    op.create_table('publisher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.Enum('IRAN', 'UNITED_STATES', 'UNITED_KINGDOM', 'GERMANY', 'FRANCE', 'JAPAN', 'CHINA', 'SOUTH_KOREA', 'INDIA', name='country'), nullable=False),
    sa.Column('founded_year', sa.Date(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publisher'))
    )
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings')),
    sa.UniqueConstraint('key', name=op.f('uq_system_settings_key'))
    )
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('isbn', sa.String(), nullable=True),
    sa.Column('edition', sa.String(length=50), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.Column('published_year', sa.Date(), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('language', sa.Enum('PERSIAN', 'ENGLISH', 'GERMAN', 'FRENCH', 'JAPANESE', 'CHINESE', 'KOREAN', 'HINDI', name='language'), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_book_genre_id_genres')),
    sa.ForeignKeyConstraint(['publisher_id'], ['publisher.id'], name=op.f('fk_book_publisher_id_publisher')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_book'))
    )
    op.create_table('book_authors',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], name=op.f('fk_book_authors_author_id_author')),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name=op.f('fk_book_authors_book_id_book')),
    sa.PrimaryKeyConstraint('book_id', 'author_id', name=op.f('pk_book_authors'))
    )
    op.create_table('copy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=False),
    sa.Column('condition', sa.Enum('GOOD', 'FAIR', 'DAMAGED', 'LOST', name='condition'), nullable=False),
    sa.Column('action', sa.Enum('REMOVED', 'BORROWED', 'FREE', 'LOANED', name='action'), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name=op.f('fk_copy_book_id_book')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_copy')),
    sa.UniqueConstraint('barcode', name=op.f('uq_copy_barcode'))
    )
    op.create_table('inventory_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('REMOVED', 'BORROWED', 'FREE', 'LOANED', name='action'), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name=op.f('fk_inventory_log_book_id_book')),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_inventory_log_member_id_members')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_log'))
    )
    op.create_table('loan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.Column('copy_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('borrowed_at', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['copy_id'], ['copy.id'], name=op.f('fk_loan_copy_id_copy')),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_loan_member_id_members')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loan'))
    )
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('copy_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BANNED', 'SUSPENDED', 'PENDING', 'DELETED', 'EXPIRED', name='status'), nullable=False),
    sa.Column('reserved_at', sa.DateTime(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['copy_id'], ['copy.id'], name=op.f('fk_reservation_copy_id_copy')),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_reservation_member_id_members')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservation'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    op.drop_table('loan')
    op.drop_table('inventory_log')
    op.drop_table('copy')
    op.drop_table('book_authors')
    op.drop_table('book')
    op.drop_table('system_settings')
    op.drop_table('publisher')
    op.drop_table('members')
    op.drop_table('genres')
    op.drop_table('author')
    # ### end Alembic commands ###
